BEGIN;

ALTER TABLE public.agendamentos
  ADD COLUMN IF NOT EXISTS desconto_valor NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_final NUMERIC(10,2);

ALTER TABLE public.clientes
  ADD COLUMN IF NOT EXISTS cartao_fidelidade_ativo BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cartao_fidelidade_carimbos INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cartao_fidelidade_meta INTEGER NOT NULL DEFAULT 10;

COMMIT;